CREATE TABLE [dbo].[DefendersTable]
(
	[USERNAME] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [FIRSTNAME] VARCHAR(50) NULL, 
    [LASTNAME] VARCHAR(50) NULL, 
    [LAWOFFICE] VARCHAR(50) NULL, 
    [EMAIL] VARCHAR(50) NULL
)
