CREATE TABLE [dbo].[DefendersTable]
(
	[USERNAME] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [FIRSTNAME] VARCHAR(50) NULL, 
    [LASTNAME] VARCHAR(50) NULL, 
    [LAWOFFICE] VARCHAR(50) NULL, 
    [EMAIL] VARCHAR(50) NULL, 
    [CONTACT] NVARCHAR(50) NULL, 
    CONSTRAINT [DEFUSERNAMEKEY] FOREIGN KEY ([USERNAME]) REFERENCES [LoginTable]([EMAIL]), 
    CONSTRAINT [LAWOFFICEKEY] FOREIGN KEY ([LAWOFFICE]) REFERENCES [LawOfficeTable]([NAME])
)
