CREATE TABLE [dbo].[EditedCasesTable]
(
	[CASENUMBER] VARCHAR(50) NOT NULL , 
    [USERNAME] VARCHAR(50) NULL, 
    [REASON] VARCHAR(MAX) NULL, 
    [DATEOFCHANGE] DATETIME NULL, 
    [IDENTIFIER] INT NOT NULL PRIMARY KEY, 
    CONSTRAINT [EDITUSERNAMEKEY] FOREIGN KEY ([USERNAME]) REFERENCES [LoginTable]([USERNAME]), 
    CONSTRAINT [CASENUMBERKEY] FOREIGN KEY ([CASENUMBER]) REFERENCES [CaseTable]([CASENUMBER])
)
