CREATE TABLE [dbo].[StaffTable]
(
    [FIRSTNAME] VARCHAR(50) NOT NULL, 
    [LASTNAME] VARCHAR(50) NOT NULL, 
    [EMAIL] VARCHAR(50) NOT NULL, 
    [DATEADDED] DATE NOT NULL, 
    CONSTRAINT [STAFFUSERNAMEKEY] FOREIGN KEY ([EMAIL]) REFERENCES [LoginTable]([EMAIL]), 
    PRIMARY KEY ([EMAIL])
)
